# Generated by Django 4.2.3 on 2023-12-16 04:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clipaddressedtopic",
            name="caregiver_relevance",
        ),
        migrations.RemoveField(
            model_name="clipaddressedtopic",
            name="information_score",
        ),
        migrations.RemoveField(
            model_name="clipaddressedtopic",
            name="inspiration_score",
        ),
        migrations.RemoveField(
            model_name="clipaddressedtopic",
            name="pwd_relevance",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="abbreviation",
        ),
        migrations.RemoveField(
            model_name="topic",
            name="category",
        ),
        migrations.AddField(
            model_name="clipaddressedtopic",
            name="instructional",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clipaddressedtopic",
            name="motivational",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="clipaddressedtopic",
            name="relevancy",
            field=models.FloatField(
                default=0.5,
                validators=[
                    django.core.validators.MinValueValidator(0.0),
                    django.core.validators.MaxValueValidator(1.0),
                ],
            ),
        ),
        migrations.AlterField(
            model_name="clipaddressedtopic",
            name="topic",
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to="app_web.topic"),
        ),
        migrations.AlterField(
            model_name="topic",
            name="name",
            field=models.CharField(max_length=32),
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32)),
                (
                    "category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.RESTRICT,
                        to="app_web.topic",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="clip",
            name="tags",
            field=models.ManyToManyField(related_name="clips", to="app_web.tag"),
        ),
    ]
