# Generated by Django 4.2.3 on 2023-12-19 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0002_remove_clipaddressedtopic_caregiver_relevance_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CareTeam",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name="CareTeamMember",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("relation", models.CharField(max_length=32)),
                ("is_careteam_admin", models.BooleanField(default=False)),
                ("member", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_web.careteam")),
            ],
        ),
        migrations.AddField(
            model_name="careteam",
            name="members",
            field=models.ManyToManyField(through="app_web.CareTeamMember", to=settings.AUTH_USER_MODEL),
        ),
    ]
