# Generated by Django 4.2.8 on 2024-01-05 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0004_rename_members_careteam_team_members_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="video",
            name="production_year",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="video",
            name="quality",
            field=models.CharField(
                choices=[("POOR", "Poor"), ("GOOD", "Good"), ("EXCELLENT", "Excellent")], default="GOOD", max_length=10
            ),
        ),
    ]
