# Generated by Django 4.2.8 on 2024-01-17 16:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0006_video_url_keytakeaway"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clip",
            name="description",
        ),
        migrations.RemoveField(
            model_name="keytakeaway",
            name="clip",
        ),
        migrations.AddField(
            model_name="clip",
            name="key_takeaways",
            field=models.ManyToManyField(blank=True, related_name="clips", to="app_web.keytakeaway"),
        ),
    ]
