# Generated by Django 4.2.8 on 2024-01-26 20:37

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0007_remove_clip_description_remove_keytakeaway_clip_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="video",
            name="url",
        ),
    ]
