# Generated by Django 4.2.8 on 2024-01-29 21:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0008_remove_video_url"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="key_takeaways",
            field=models.ManyToManyField(
                blank=True, related_name="clips", to="app_web.keytakeaway", verbose_name="Takeaways"
            ),
        ),
        migrations.AlterField(
            model_name="clip",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="clips", to="app_web.tag", verbose_name="Tags"),
        ),
        migrations.CreateModel(
            name="Resource",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                ("description", models.TextField()),
                ("link", models.URLField()),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("ARTICLE", "Article"),
                            ("BROCHURE", "Brochure"),
                            ("WORKSHEET", "Worksheet"),
                            ("WORKBOOK", "Workbook"),
                            ("BOOK", "Book"),
                            ("WEB_TOOL", "Web Tool"),
                        ],
                        max_length=10,
                    ),
                ),
                ("is_free", models.BooleanField(default=True)),
                ("requires_account", models.BooleanField(default=False)),
                (
                    "topics",
                    models.ManyToManyField(
                        blank=True, related_name="resources", to="app_web.topic", verbose_name="Topics"
                    ),
                ),
            ],
        ),
    ]
