# Generated by Django 4.2.8 on 2024-02-07 17:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0009_alter_clip_key_takeaways_alter_clip_tags_resource"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channel",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="clip",
            name="name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="video",
            name="name",
            field=models.CharField(max_length=255),
        ),
    ]
