# Generated by Django 4.2.8 on 2024-02-06 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0009_alter_clip_key_takeaways_alter_clip_tags_resource"),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("title", models.CharField(max_length=128)),
                ("short_description", models.TextField()),
                ("full_description", models.TextField()),
                (
                    "related_resources",
                    models.ManyToManyField(
                        blank=True, related_name="resources", to="app_web.resource", verbose_name="Resources"
                    ),
                ),
                (
                    "related_tags",
                    models.ManyToManyField(blank=True, related_name="tags", to="app_web.tag", verbose_name="Tags"),
                ),
                (
                    "related_terms",
                    models.ManyToManyField(
                        blank=True, related_name="terms", to="app_web.glossaryterm", verbose_name="Glossary Terms"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="TaskField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("label", models.CharField(max_length=64)),
                ("description", models.TextField(blank=True)),
                ("required", models.BooleanField(default=False)),
                ("type", models.CharField(choices=[("TEXTAREA", "Textarea"), ("INPUT", "Input")], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name="TeamTaskField",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("value", models.TextField(blank=True, default="")),
                ("task_field", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_web.taskfield")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_web.careteam")),
            ],
        ),
        migrations.DeleteModel(
            name="Field",
        ),
        migrations.AddField(
            model_name="task",
            name="task_fields",
            field=models.ManyToManyField(
                blank=True, related_name="task_fields", to="app_web.taskfield", verbose_name="Task Fields"
            ),
        ),
        migrations.AddField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_web.topic"),
        ),
        migrations.AddField(
            model_name="careteam",
            name="task_fields",
            field=models.ManyToManyField(related_name="team", through="app_web.TeamTaskField", to="app_web.taskfield"),
        ),
    ]
