# Generated by Django 4.2.3 on 2024-02-08 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0010_alter_channel_name_alter_clip_name_alter_video_name'),
        ('app_web', '0010_task_taskfield_teamtaskfield_delete_field_and_more'),
    ]

    operations = [
    ]
