# Generated by Django 4.2.3 on 2024-02-13 17:21

import app_web.models
import ckeditor.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app_web', '0011_merge_20240208_1530'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='task_fields',
        ),
        migrations.AddField(
            model_name='taskfield',
            name='task',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_web.task'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='task',
            name='full_description',
            field=ckeditor.fields.RichTextField(validators=[app_web.models.validate_full_description]),
        ),
    ]
