# Generated by Django 4.2.3 on 2024-02-26 16:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0013_teamtaskfield_completed_timestamp_teamtaskfield_user"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="teamtaskfield",
            unique_together={("team", "task_field")},
        ),
    ]
