# Generated by Django 4.2.10 on 2024-02-28 17:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0014_alter_teamtaskfield_unique_together"),
    ]

    operations = [
        migrations.AddField(
            model_name="careteam",
            name="caree",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="caregivers",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="careteam",
            name="is_setup_complete",
            field=models.BooleanField(default=False),
        ),
    ]
