# Generated by Django 4.2.10 on 2024-02-28 19:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0015_careteam_caree_careteam_is_setup_complete"),
    ]

    operations = [
        migrations.RenameField(
            model_name="clipreviewrequest",
            old_name="reviewer_notes",
            new_name="note",
        ),
        migrations.RemoveField(
            model_name="clipreviewrequest",
            name="closed",
        ),
        migrations.RemoveField(
            model_name="clipreviewrequest",
            name="curator",
        ),
        migrations.RemoveField(
            model_name="clipreviewrequest",
            name="curator_notes",
        ),
        migrations.RemoveField(
            model_name="clipreviewrequest",
            name="reviewer",
        ),
        migrations.AddField(
            model_name="clipreviewrequest",
            name="requester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.RESTRICT,
                related_name="requester",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.CreateModel(
            name="ClipReview",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("timestamp", models.DateTimeField(blank=True, null=True)),
                ("note", models.TextField(blank=True, null=True)),
                (
                    "request",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="request",
                        to="app_web.clipreviewrequest",
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.RESTRICT,
                        related_name="reviewer",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
