# Generated by Django 4.2.10 on 2024-03-05 19:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0017_note"),
    ]

    operations = [
        migrations.CreateModel(
            name="FeaturedClip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "clip",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="featured_clip", to="app_web.clip"
                    ),
                ),
            ],
        ),
    ]
