# Generated by Django 4.2.10 on 2024-03-07 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0018_featuredclip"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="tags",
            field=models.ManyToManyField(blank=True, related_name="resources", to="app_web.tag", verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="task",
            name="related_resources",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="app_web.resource", verbose_name="Resources"
            ),
        ),
        migrations.AlterField(
            model_name="task",
            name="related_tags",
            field=models.ManyToManyField(blank=True, related_name="tasks", to="app_web.tag", verbose_name="Tags"),
        ),
        migrations.AlterField(
            model_name="task",
            name="related_terms",
            field=models.ManyToManyField(
                blank=True, related_name="tasks", to="app_web.glossaryterm", verbose_name="Glossary Terms"
            ),
        ),
    ]
