# Generated by Django 4.2.10 on 2024-03-07 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_web", "0019_resource_tags_alter_task_related_resources_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="careteam",
            name="caree",
        ),
        migrations.AddField(
            model_name="careteammember",
            name="is_caree",
            field=models.BooleanField(default=False),
        ),
    ]
