# Generated by Django 4.2.10 on 2024-03-29 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0021_priority_task_is_setup_question_task_ranking"),
    ]

    operations = [
        migrations.AddField(
            model_name="careteam",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
