# Generated by Django 4.2.10 on 2024-04-01 18:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0022_careteam_deleted_at"),
        ("app_web", "0022_teamtaskcompleted"),
    ]

    operations = []
