# Generated by Django 4.2.10 on 2024-04-09 20:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0023_merge_0022_careteam_deleted_at_0022_teamtaskcompleted"),
    ]

    operations = [
        migrations.CreateModel(
            name="ClipUser",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("saved", models.BooleanField(default=False)),
                ("saved_timestamp", models.DateTimeField(blank=True, null=True)),
                ("watched", models.BooleanField(default=False)),
                ("watched_timestamp", models.DateTimeField(blank=True, null=True)),
                ("clip", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_web.clip")),
                ("user", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
