# Generated by Django 4.2.10 on 2024-04-15 20:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0024_clipuser"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clipuser",
            name="clip",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="user_info", to="app_web.clip"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clipuser",
            unique_together={("clip", "user")},
        ),
    ]
