# Generated by Django 4.2.10 on 2024-04-17 16:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0025_alter_clipuser_clip_alter_clipuser_unique_together"),
    ]

    operations = [
        migrations.CreateModel(
            name="TeamTask",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("modified_timestamp", models.DateTimeField(blank=True, null=True)),
                ("completed_timestamp", models.DateTimeField(blank=True, null=True)),
                ("task", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_web.task")),
                ("team", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="app_web.careteam")),
            ],
        ),
        migrations.DeleteModel(
            name="TeamTaskCompleted",
        ),
    ]
