# Generated by Django 4.2.10 on 2024-04-23 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0026_teamtask_delete_teamtaskcompleted"),
    ]

    operations = [
        migrations.AddField(
            model_name="careteammember",
            name="notification_count",
            field=models.IntegerField(default=0),
        ),
    ]
