# Generated by Django 4.2.10 on 2024-04-25 19:58

from django.db import migrations


def create_system_user(apps, schema_editor):
    # create the system user
    User = apps.get_model('app_web', 'User')
    system_user = User.objects.create()

    # should always be the first user
    system_user.id = 1
    system_user.first_name = "Finle"
    system_user.last_name = ""
    system_user.email = "finle@finle.com"
    system_user.save()


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0028_alter_clipreview_reviewer_and_more"),
    ]

    operations = [migrations.RunPython(create_system_user)]
