# Generated by Django 4.2.10 on 2024-04-26 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0029_auto_20240425_1958"),
    ]

    operations = [
        migrations.AddField(
            model_name="clipuser",
            name="rating",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
