# Generated by Django 4.2.10 on 2024-05-15 16:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0031_accesstoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="resource",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="app_web.resource"
            ),
        ),
    ]
