# Generated by Django 4.2.10 on 2024-05-17 14:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0032_note_resource"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="resource",
            name="tags",
        ),
        migrations.RemoveField(
            model_name="resource",
            name="topics",
        ),
        migrations.AlterField(
            model_name="task",
            name="topic",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="app_web.topic"
            ),
        ),
    ]
