# Generated by Django 4.2.10 on 2024-05-21 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0033_remove_resource_tags_remove_resource_topics_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="note",
            name="task",
            field=models.ForeignKey(
                blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to="app_web.task"
            ),
        ),
    ]
