# Generated by Django 4.2.10 on 2024-07-03 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0034_note_task"),
    ]

    operations = [
        migrations.AddField(
            model_name="clip",
            name="archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="video",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
