# Generated by Django 4.2.10 on 2024-07-08 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0035_clip_archived_video_archived"),
    ]

    operations = [
        migrations.AddField(
            model_name="resource",
            name="file",
            field=models.FileField(blank=True, null=True, upload_to="resources/"),
        ),
        migrations.AlterField(
            model_name="resource",
            name="link",
            field=models.URLField(blank=True, null=True),
        ),
    ]
