# Generated by Django 4.2.10 on 2024-07-17 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0036_resource_file_alter_resource_link"),
    ]

    operations = [
        migrations.AddField(
            model_name="topic",
            name="archived",
            field=models.BooleanField(default=False),
        ),
    ]
