# Generated by Django 4.2.10 on 2024-09-03 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0038_alter_task_topic"),
    ]

    operations = [
        migrations.AddField(
            model_name="clip",
            name="speaker",
            field=models.CharField(blank=True, max_length=32),
        ),
    ]
