# Generated by Django 4.2.10 on 2024-09-10 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_web", "0039_clip_speaker"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clip",
            name="speaker",
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
